<?php
  return [
    ["name"=>"article 1","text"=>"lorem ipsum 1","url"=>"art1"],
    ["name"=>"article 2","text"=>"lorem ipsum 2","url"=>"art2"],
    ["name"=>"article 3","text"=>"lorem ipsum 3","url"=>"art3"],
    ["name"=>"article 4","text"=>"lorem ipsum 4","url"=>"art4"],
    ["name"=>"article 5","text"=>"lorem ipsum 5","url"=>"art5"],
    ["name"=>"article 6","text"=>"lorem ipsum 6","url"=>"art6"],
    ["name"=>"article 7","text"=>"lorem ipsum 7","url"=>"art7"],
    ["name"=>"article 8","text"=>"lorem ipsum 8","url"=>"art8"],
    ["name"=>"article 9","text"=>"lorem ipsum 9","url"=>"art9"],
    ["name"=>"article 10","text"=>"lorem ipsum 10","url"=>"art10"],
    ["name"=>"article 11","text"=>"lorem ipsum 11","url"=>"art11"],
    ["name"=>"article 12","text"=>"lorem ipsum 12","url"=>"art12"],
    ["name"=>"article 13","text"=>"lorem ipsum 13","url"=>"art13"],
    ["name"=>"article 14","text"=>"lorem ipsum 14","url"=>"art14"],
    ["name"=>"article 15","text"=>"lorem ipsum 15","url"=>"art15"],
    ["name"=>"article 16","text"=>"lorem ipsum 16","url"=>"art16"],
    ["name"=>"article 17","text"=>"lorem ipsum 17","url"=>"art17"],
    ["name"=>"article 18","text"=>"lorem ipsum 18","url"=>"art18"],
    ["name"=>"article 19","text"=>"lorem ipsum 19","url"=>"art19"],
    ["name"=>"article 20","text"=>"lorem ipsum 20","url"=>"art20"],
    ["name"=>"article 21","text"=>"lorem ipsum 21","url"=>"art21"],
    ["name"=>"article 22","text"=>"lorem ipsum 22","url"=>"art22"],
    ["name"=>"article 23","text"=>"lorem ipsum 23","url"=>"art23"],
    ["name"=>"article 24","text"=>"lorem ipsum 24","url"=>"art24"],
    ["name"=>"article 25","text"=>"lorem ipsum 25","url"=>"art25"],
    ["name"=>"article 26","text"=>"lorem ipsum 26","url"=>"art26"],
    ["name"=>"article 27","text"=>"lorem ipsum 27","url"=>"art27"],
    ["name"=>"article 28","text"=>"lorem ipsum 28","url"=>"art28"],
    ["name"=>"article 29","text"=>"lorem ipsum 29","url"=>"art29"],
    ["name"=>"article 30","text"=>"lorem ipsum 30","url"=>"art30"],
    ["name"=>"article 31","text"=>"lorem ipsum 31","url"=>"art31"],
    ["name"=>"article 32","text"=>"lorem ipsum 32","url"=>"art32"],
    ["name"=>"article 33","text"=>"lorem ipsum 33","url"=>"art33"],
  ]
 ?>
